version: "3.8"
services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
        - my-network
  web:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
        - my-network

networks:
    my-network: